// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcmnntlyjhomkqjvuemg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjbW5udGx5amhvbWtxanZ1ZW1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxODcxNjAsImV4cCI6MjA2OTc2MzE2MH0.AhEeqG13vpFqZDf8gYb9s6IIJ9NLnwlDXYuQMliC57s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});